from __future__ import annotations

import csv
import io
import os
import sqlite3
from datetime import date, datetime
from functools import wraps
from pathlib import Path

from flask import (
    Flask,
    flash,
    g,
    redirect,
    render_template,
    request,
    send_file,
    session,
    url_for,
)
from werkzeug.security import check_password_hash, generate_password_hash


BASE_DIR = Path(__file__).resolve().parent
DATABASE = BASE_DIR / "finance.db"
DATABASE_URL = os.environ.get("DATABASE_URL")

app = Flask(__name__)
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "dev-change-this-secret")
app.config["DATABASE"] = DATABASE
app.config["DATABASE_URL"] = DATABASE_URL

CATEGORIES = [
    "Beignets",
    "Transport",
    "Paris sportifs",
    "Alimentation",
    "Chantier",
    "Autres revenus",
    "Épargne",
    "Autres",
]


def get_db() -> sqlite3.Connection:
    if "db" not in g:
        if app.config["DATABASE_URL"]:
            import psycopg2
            from psycopg2.extras import DictCursor

            database_url = app.config["DATABASE_URL"].replace(
                "postgres://", "postgresql://", 1
            )
            g.db = psycopg2.connect(database_url, cursor_factory=DictCursor)
        else:
            g.db = sqlite3.connect(app.config["DATABASE"])
            g.db.row_factory = sqlite3.Row
            g.db.execute("PRAGMA foreign_keys = ON")
    return g.db


def execute(sql: str, parameters=()):
    """Use the same query source for local SQLite and hosted PostgreSQL."""
    if app.config["DATABASE_URL"]:
        sql = sql.replace("?", "%s")
    return get_db().execute(sql, parameters)


@app.teardown_appcontext
def close_db(_error: BaseException | None) -> None:
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db() -> None:
    db = get_db()
    schema = """
        CREATE TABLE IF NOT EXISTS users (
            id {id_type} PRIMARY KEY,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS transactions (
            id {id_type} PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            kind TEXT NOT NULL CHECK(kind IN ('income', 'expense')),
            amount REAL NOT NULL CHECK(amount > 0),
            category TEXT NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            transaction_date TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS budgets (
            id {id_type} PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            category TEXT NOT NULL,
            amount REAL NOT NULL CHECK(amount > 0),
            month TEXT NOT NULL,
            UNIQUE(user_id, category, month)
        );
        """.format(
        id_type=(
            "INTEGER GENERATED BY DEFAULT AS IDENTITY"
            if app.config["DATABASE_URL"]
            else "INTEGER"
        )
    )
    if app.config["DATABASE_URL"]:
        with db.cursor() as cursor:
            cursor.execute(schema)
    else:
        db.executescript(schema)
    db.commit()


@app.before_request
def prepare_request() -> None:
    init_db()
    g.user = None
    user_id = session.get("user_id")
    if user_id is not None:
        g.user = execute(
            "SELECT id, email FROM users WHERE id = ?", (user_id,)
        ).fetchone()


def login_required(view):
    @wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            flash("Connectez-vous pour accéder à cette page.", "warning")
            return redirect(url_for("login"))
        return view(*args, **kwargs)

    return wrapped_view


def suggest_category(description: str, kind: str) -> str:
    if kind == "income":
        return "Chantier" if "chantier" in description.lower() else "Autres revenus"
    keywords = {
        "Paris sportifs": ("pari", "paris", "bet", "cote", "cotes", "football", "foot"),
        "Beignets": ("beignet", "beignets", "pain", "petit déjeuner", "petit dejeuner"),
        "Transport": ("moto", "taxi", "essence", "bus", "transport"),
        "Alimentation": ("courses", "restaurant", "repas", "marché", "marche"),
    }
    text = description.lower()
    for category, terms in keywords.items():
        if any(term in text for term in terms):
            return category
    return "Autres"


def month_bounds(month: str) -> tuple[str, str]:
    year, month_number = (int(value) for value in month.split("-"))
    if month_number == 12:
        next_month = date(year + 1, 1, 1)
    else:
        next_month = date(year, month_number + 1, 1)
    return f"{year:04d}-{month_number:02d}-01", next_month.isoformat()


@app.template_filter("xaf")
def format_xaf(value: float | int) -> str:
    return f"{value:,.0f}".replace(",", " ") + " FCFA"


@app.route("/")
def index():
    return redirect(url_for("dashboard" if g.user else "login"))


@app.route("/register", methods=("GET", "POST"))
def register():
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")
        if not email or "@" not in email:
            flash("Saisissez une adresse e-mail valide.", "danger")
        elif len(password) < 8:
            flash("Le mot de passe doit contenir au moins 8 caractères.", "danger")
        else:
            try:
                db = get_db()
                execute(
                    "INSERT INTO users (email, password_hash) VALUES (?, ?)",
                    (email, generate_password_hash(password)),
                )
                db.commit()
                flash("Compte créé. Vous pouvez maintenant vous connecter.", "success")
                return redirect(url_for("login"))
            except sqlite3.IntegrityError:
                flash("Cette adresse e-mail est déjà utilisée.", "danger")
    return render_template("login.html", mode="register")


@app.route("/login", methods=("GET", "POST"))
def login():
    if request.method == "POST":
        user = execute(
            "SELECT * FROM users WHERE email = ?", (request.form.get("email", "").strip().lower(),)
        ).fetchone()
        if user is None or not check_password_hash(user["password_hash"], request.form.get("password", "")):
            flash("E-mail ou mot de passe incorrect.", "danger")
        else:
            session.clear()
            session["user_id"] = user["id"]
            return redirect(url_for("dashboard"))
    return render_template("login.html", mode="login")


@app.post("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


@app.route("/dashboard")
@login_required
def dashboard():
    month = request.args.get("month", date.today().strftime("%Y-%m"))
    start, end = month_bounds(month)
    db = get_db()
    totals = execute(
        """
        SELECT kind, COALESCE(SUM(amount), 0) AS total
        FROM transactions
        WHERE user_id = ? AND transaction_date >= ? AND transaction_date < ?
        GROUP BY kind
        """,
        (g.user["id"], start, end),
    ).fetchall()
    total_map = {row["kind"]: row["total"] for row in totals}
    expenses = execute(
        """
        SELECT category, SUM(amount) AS total
        FROM transactions
        WHERE user_id = ? AND kind = 'expense'
          AND transaction_date >= ? AND transaction_date < ?
        GROUP BY category ORDER BY total DESC
        """,
        (g.user["id"], start, end),
    ).fetchall()
    betting_total = execute(
        """
        SELECT COALESCE(SUM(amount), 0) FROM transactions
        WHERE user_id = ? AND kind = 'expense' AND category = 'Paris sportifs'
          AND transaction_date >= ? AND transaction_date < ?
        """,
        (g.user["id"], start, end),
    ).fetchone()[0]
    recent = execute(
        "SELECT * FROM transactions WHERE user_id = ? ORDER BY transaction_date DESC, id DESC LIMIT 8",
        (g.user["id"],),
    ).fetchall()
    budgets = execute(
        "SELECT * FROM budgets WHERE user_id = ? AND month = ?", (g.user["id"], month)
    ).fetchall()
    spent_by_category = {
        row["category"]: row["total"]
        for row in execute(
            """
            SELECT category, SUM(amount) AS total FROM transactions
            WHERE user_id = ? AND kind = 'expense'
              AND transaction_date >= ? AND transaction_date < ?
            GROUP BY category
            """,
            (g.user["id"], start, end),
        ).fetchall()
    }
    budget_status = [
        {**dict(budget), "spent": spent_by_category.get(budget["category"], 0)}
        for budget in budgets
    ]
    return render_template(
        "dashboard.html",
        month=month,
        income=total_map.get("income", 0),
        expenses_total=total_map.get("expense", 0),
        balance=total_map.get("income", 0) - total_map.get("expense", 0),
        betting_total=betting_total,
        expenses=expenses,
        recent=recent,
        budget_status=budget_status,
    )


@app.route("/transactions", methods=("GET", "POST"))
@login_required
def transactions():
    db = get_db()
    if request.method == "POST":
        kind = request.form.get("kind", "expense")
        description = request.form.get("description", "").strip()
        category = request.form.get("category") or suggest_category(description, kind)
        try:
            amount = float(request.form.get("amount", "0"))
            transaction_date = datetime.strptime(
                request.form.get("transaction_date", ""), "%Y-%m-%d"
            ).date().isoformat()
            if kind not in {"income", "expense"} or amount <= 0:
                raise ValueError
        except (TypeError, ValueError):
            flash("Vérifiez le type, le montant et la date.", "danger")
        else:
            execute(
                """
                INSERT INTO transactions
                    (user_id, kind, amount, category, description, transaction_date)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (g.user["id"], kind, amount, category, description, transaction_date),
            )
            db.commit()
            flash("Transaction ajoutée.", "success")
            return redirect(url_for("transactions"))
    rows = execute(
        "SELECT * FROM transactions WHERE user_id = ? ORDER BY transaction_date DESC, id DESC",
        (g.user["id"],),
    ).fetchall()
    return render_template(
        "transactions.html",
        transactions=rows,
        categories=CATEGORIES,
        today=date.today().isoformat(),
    )


@app.post("/transactions/<int:transaction_id>/delete")
@login_required
def delete_transaction(transaction_id: int):
    execute(
        "DELETE FROM transactions WHERE id = ? AND user_id = ?",
        (transaction_id, g.user["id"]),
    )
    get_db().commit()
    flash("Transaction supprimée.", "success")
    return redirect(url_for("transactions"))


@app.route("/budgets", methods=("GET", "POST"))
@login_required
def budgets():
    month = request.values.get("month", date.today().strftime("%Y-%m"))
    db = get_db()
    if request.method == "POST":
        try:
            amount = float(request.form.get("amount", "0"))
            category = request.form["category"]
            if amount <= 0 or category not in CATEGORIES:
                raise ValueError
            execute(
                """
                INSERT INTO budgets (user_id, category, amount, month) VALUES (?, ?, ?, ?)
                ON CONFLICT(user_id, category, month)
                DO UPDATE SET amount = excluded.amount
                """,
                (g.user["id"], category, amount, month),
            )
            db.commit()
            flash("Budget enregistré.", "success")
        except (KeyError, ValueError):
            flash("Saisissez une catégorie et un montant valides.", "danger")
        return redirect(url_for("budgets", month=month))
    rows = execute(
        "SELECT * FROM budgets WHERE user_id = ? AND month = ? ORDER BY category",
        (g.user["id"], month),
    ).fetchall()
    start, end = month_bounds(month)
    budget_status = []
    for row in rows:
        spent = execute(
            """
            SELECT COALESCE(SUM(amount), 0) FROM transactions
            WHERE user_id = ? AND kind = 'expense' AND category = ?
              AND transaction_date >= ? AND transaction_date < ?
            """,
            (g.user["id"], row["category"], start, end),
        ).fetchone()[0]
        budget_status.append({**dict(row), "spent": spent})
    return render_template(
        "budgets.html", budgets=budget_status, month=month, categories=CATEGORIES
    )


@app.get("/export/csv")
@login_required
def export_csv():
    rows = execute(
        """
        SELECT transaction_date, kind, category, description, amount
        FROM transactions WHERE user_id = ? ORDER BY transaction_date DESC
        """,
        (g.user["id"],),
    ).fetchall()
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["date", "type", "categorie", "description", "montant"])
    writer.writerows(
        (row["transaction_date"], row["kind"], row["category"], row["description"], row["amount"])
        for row in rows
    )
    return send_file(
        io.BytesIO(output.getvalue().encode("utf-8-sig")),
        mimetype="text/csv",
        as_attachment=True,
        download_name="rapport-finances.csv",
    )


@app.get("/export/xlsx")
@login_required
def export_xlsx():
    try:
        from openpyxl import Workbook
    except ImportError:
        flash("L'export Excel nécessite l'installation des dépendances.", "danger")
        return redirect(url_for("dashboard"))

    rows = execute(
        """
        SELECT transaction_date, kind, category, description, amount
        FROM transactions WHERE user_id = ? ORDER BY transaction_date DESC
        """,
        (g.user["id"],),
    ).fetchall()
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Transactions"
    sheet.append(["Date", "Type", "Catégorie", "Description", "Montant (€)"])
    for row in rows:
        sheet.append(
            [row["transaction_date"], row["kind"], row["category"], row["description"], row["amount"]]
        )
    sheet.freeze_panes = "A2"
    sheet.auto_filter.ref = sheet.dimensions
    for column in sheet.columns:
        width = max(len(str(cell.value or "")) for cell in column) + 2
        sheet.column_dimensions[column[0].column_letter].width = min(width, 35)
    output = io.BytesIO()
    workbook.save(output)
    output.seek(0)
    return send_file(
        output,
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        as_attachment=True,
        download_name="rapport-finances.xlsx",
    )


@app.get("/export/report")
@login_required
def export_report():
    month = request.args.get("month", date.today().strftime("%Y-%m"))
    start, end = month_bounds(month)
    rows = execute(
        """
        SELECT transaction_date, kind, category, description, amount
        FROM transactions
        WHERE user_id = ? AND transaction_date >= ? AND transaction_date < ?
        ORDER BY transaction_date DESC
        """,
        (g.user["id"], start, end),
    ).fetchall()
    income = sum(row["amount"] for row in rows if row["kind"] == "income")
    expenses = sum(row["amount"] for row in rows if row["kind"] == "expense")
    return render_template(
        "report.html", month=month, rows=rows, income=income, expenses=expenses
    )


if __name__ == "__main__":
    with app.app_context():
        init_db()
    app.run(debug=os.environ.get("FLASK_DEBUG") == "1")
