from __future__ import annotations

import os
import re
import secrets
import sqlite3
from functools import wraps
from pathlib import Path

from flask import Flask, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

BASE_DIR = Path(__file__).resolve().parent
DATABASE = BASE_DIR / "linkboutik.db"
DATABASE_URL = os.environ.get("DATABASE_URL")
PRODUCT_CATEGORIES = ["Alimentation", "Mode", "Beauté", "Maison", "Téléphones", "Services", "Autres"]

app = Flask(__name__)
app.config.update(
    SECRET_KEY=os.environ.get("SECRET_KEY", "dev-change-this-secret"),
    DATABASE=DATABASE,
    DATABASE_URL=DATABASE_URL,
)


def get_db():
    if "db" not in g:
        if app.config["DATABASE_URL"]:
            import psycopg2
            from psycopg2.extras import DictCursor

            url = app.config["DATABASE_URL"].replace("postgres://", "postgresql://", 1)
            g.db = psycopg2.connect(url, cursor_factory=DictCursor)
        else:
            g.db = sqlite3.connect(app.config["DATABASE"])
            g.db.row_factory = sqlite3.Row
            g.db.execute("PRAGMA foreign_keys = ON")
    return g.db


def execute(sql: str, parameters=()):
    if app.config["DATABASE_URL"]:
        cursor = get_db().cursor()
        cursor.execute(sql.replace("?", "%s"), parameters)
        return cursor
    return get_db().execute(sql, parameters)


@app.teardown_appcontext
def close_db(_error):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    db = get_db()
    id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY" if app.config["DATABASE_URL"] else "INTEGER"
    schema = f"""
        CREATE TABLE IF NOT EXISTS users (
            id {id_type} PRIMARY KEY, email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS shops (
            id {id_type} PRIMARY KEY, user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
            name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT NOT NULL DEFAULT '',
            phone TEXT NOT NULL DEFAULT '', whatsapp TEXT NOT NULL DEFAULT '',
            location TEXT NOT NULL DEFAULT '', hours TEXT NOT NULL DEFAULT '',
            logo_url TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS products (
            id {id_type} PRIMARY KEY, shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
            name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', price REAL NOT NULL CHECK(price > 0),
            category TEXT NOT NULL DEFAULT 'Autres', image_url TEXT NOT NULL DEFAULT '',
            stock INTEGER NOT NULL DEFAULT 0 CHECK(stock >= 0), is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS orders (
            id {id_type} PRIMARY KEY, shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
            product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
            quantity INTEGER NOT NULL CHECK(quantity > 0), customer_name TEXT NOT NULL,
            customer_phone TEXT NOT NULL, note TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'new', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    """
    if app.config["DATABASE_URL"]:
        with db.cursor() as cursor:
            for statement in schema.split(";"):
                if statement.strip():
                    cursor.execute(statement)
    else:
        db.executescript(schema)
    db.commit()


@app.before_request
def prepare_request():
    init_db()
    g.user = None
    if session.get("user_id") is not None:
        g.user = execute("SELECT id, email FROM users WHERE id = ?", (session["user_id"],)).fetchone()


def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if g.user is None:
            flash("Connecte-toi pour gérer ta boutique.", "warning")
            return redirect(url_for("login"))
        return view(*args, **kwargs)
    return wrapped


def make_slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower().strip()).strip("-") or f"boutique-{secrets.token_hex(3)}"


@app.template_filter("xaf")
def format_xaf(value):
    return f"{value:,.0f}".replace(",", " ") + " FCFA"


@app.route("/")
def index():
    return redirect(url_for("dashboard")) if g.user else render_template("landing.html")


@app.route("/register", methods=("GET", "POST"))
def register():
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")
        if "@" not in email:
            flash("Saisis une adresse e-mail valide.", "danger")
        elif len(password) < 8:
            flash("Le mot de passe doit contenir au moins 8 caractères.", "danger")
        else:
            try:
                execute("INSERT INTO users (email, password_hash) VALUES (?, ?)", (email, generate_password_hash(password)))
                get_db().commit()
                flash("Compte créé. Tu peux maintenant te connecter.", "success")
                return redirect(url_for("login"))
            except sqlite3.IntegrityError:
                flash("Cette adresse e-mail est déjà utilisée.", "danger")
    return render_template("login.html", mode="register")


@app.route("/login", methods=("GET", "POST"))
def login():
    if request.method == "POST":
        user = execute("SELECT * FROM users WHERE email = ?", (request.form.get("email", "").strip().lower(),)).fetchone()
        if user is None or not check_password_hash(user["password_hash"], request.form.get("password", "")):
            flash("E-mail ou mot de passe incorrect.", "danger")
        else:
            session.clear()
            session["user_id"] = user["id"]
            return redirect(url_for("dashboard"))
    return render_template("login.html", mode="login")


@app.post("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


@app.route("/dashboard", methods=("GET", "POST"))
@login_required
def dashboard():
    shop = execute("SELECT * FROM shops WHERE user_id = ?", (g.user["id"],)).fetchone()
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        if not name:
            flash("Donne un nom à ta boutique.", "danger")
        else:
            slug = make_slug(request.form.get("slug") or name)
            if execute("SELECT id FROM shops WHERE slug = ? AND user_id != ?", (slug, g.user["id"])).fetchone():
                slug = f"{slug}-{secrets.token_hex(2)}"
            values = (name, slug, request.form.get("description", "").strip(), request.form.get("phone", "").strip(),
                      request.form.get("whatsapp", "").strip(), request.form.get("location", "").strip(),
                      request.form.get("hours", "").strip(), request.form.get("logo_url", "").strip())
            if shop:
                execute("UPDATE shops SET name=?,slug=?,description=?,phone=?,whatsapp=?,location=?,hours=?,logo_url=? WHERE id=? AND user_id=?",
                        (*values, shop["id"], g.user["id"]))
            else:
                execute("INSERT INTO shops (user_id,name,slug,description,phone,whatsapp,location,hours,logo_url) VALUES (?,?,?,?,?,?,?,?,?)",
                        (g.user["id"], *values))
            get_db().commit()
            flash("Ta boutique est publiée.", "success")
            return redirect(url_for("dashboard"))
    shop = execute("SELECT * FROM shops WHERE user_id = ?", (g.user["id"],)).fetchone()
    products = execute("SELECT * FROM products WHERE shop_id = ? ORDER BY id DESC", (shop["id"],)).fetchall() if shop else []
    orders = execute("SELECT orders.*, products.name AS product_name FROM orders JOIN products ON products.id=orders.product_id WHERE orders.shop_id=? ORDER BY orders.id DESC LIMIT 20",
                     (shop["id"],)).fetchall() if shop else []
    return render_template("dashboard.html", shop=shop, products=products, orders=orders, categories=PRODUCT_CATEGORIES)


@app.post("/products")
@login_required
def create_product():
    shop = execute("SELECT id FROM shops WHERE user_id = ?", (g.user["id"],)).fetchone()
    if not shop:
        flash("Crée d'abord ta boutique.", "warning")
        return redirect(url_for("dashboard"))
    try:
        name, price, stock = request.form.get("name", "").strip(), float(request.form.get("price", "0")), int(request.form.get("stock", "0"))
        if not name or price <= 0 or stock < 0:
            raise ValueError
    except ValueError:
        flash("Vérifie le nom, le prix et le stock.", "danger")
        return redirect(url_for("dashboard"))
    execute("INSERT INTO products (shop_id,name,description,price,category,image_url,stock) VALUES (?,?,?,?,?,?,?)",
            (shop["id"], name, request.form.get("description", "").strip(), price, request.form.get("category", "Autres"),
             request.form.get("image_url", "").strip(), stock))
    get_db().commit()
    flash("Produit ajouté.", "success")
    return redirect(url_for("dashboard"))


@app.post("/products/<int:product_id>/delete")
@login_required
def delete_product(product_id):
    execute("DELETE FROM products WHERE id=? AND shop_id IN (SELECT id FROM shops WHERE user_id=?)", (product_id, g.user["id"]))
    get_db().commit()
    flash("Produit supprimé.", "success")
    return redirect(url_for("dashboard"))


@app.route("/boutique/<slug>", methods=("GET", "POST"))
def public_shop(slug):
    shop = execute("SELECT * FROM shops WHERE slug = ?", (slug,)).fetchone()
    if shop is None:
        return render_template("not_found.html"), 404
    if request.method == "POST":
        try:
            product_id, quantity = int(request.form["product_id"]), int(request.form.get("quantity", "1"))
            product = execute("SELECT * FROM products WHERE id=? AND shop_id=? AND is_active=TRUE", (product_id, shop["id"])).fetchone()
            name, phone = request.form.get("customer_name", "").strip(), request.form.get("customer_phone", "").strip()
            if product is None or quantity < 1 or quantity > product["stock"] or not name or not phone:
                raise ValueError
            execute("INSERT INTO orders (shop_id,product_id,quantity,customer_name,customer_phone,note) VALUES (?,?,?,?,?,?)",
                    (shop["id"], product_id, quantity, name, phone, request.form.get("note", "").strip()))
            execute("UPDATE products SET stock=stock-? WHERE id=?", (quantity, product_id))
            get_db().commit()
            flash("Commande envoyée au commerçant.", "success")
        except (KeyError, ValueError):
            flash("Vérifie le produit, la quantité et tes coordonnées.", "danger")
    products = execute("SELECT * FROM products WHERE shop_id=? AND is_active=TRUE ORDER BY id DESC", (shop["id"],)).fetchall()
    return render_template("public_shop.html", shop=shop, products=products)


if __name__ == "__main__":
    with app.app_context():
        init_db()
    app.run(debug=os.environ.get("FLASK_DEBUG") == "1")
